qbs = [
    {'time': '', 'opp': '', 'name': 'Aaron Rodgers', 'team': 'GB'},
    {'time': '', 'opp': '', 'name': 'Andrew Luck', 'team': 'IND'},
    {'time': '', 'opp': '', 'name': 'Drew Brees', 'team': 'NO'},
    {'time': '', 'opp': '', 'name': 'Peyton Manning', 'team': 'DEN'},
    {'time': '', 'opp': '', 'name': 'Russell Wilson', 'team': 'SEA'},
    {'time': '', 'opp': '', 'name': 'Matthew Stafford', 'team': 'DET'},
    {'time': '', 'opp': '', 'name': 'Tom Brady', 'team': 'NE'},
    {'time': '', 'opp': '', 'name': 'Cam Newton', 'team': 'CAR'},
    {'time': '', 'opp': '', 'name': 'Tony Romo', 'team': 'DAL'},
    {'time': '', 'opp': '', 'name': 'Ben Roethlisberger', 'team': 'PIT'},
    {'time': '', 'opp': '', 'name': 'Matt Ryan', 'team': 'ATL'},
    {'time': '', 'opp': '', 'name': 'Derek Carr', 'team': 'OAK'},
    {'time': '', 'opp': '', 'name': 'Phillip Rivers', 'team': 'SD'},
    {'time': '', 'opp': '', 'name': 'Johnny Manziel', 'team': 'CLE'},
    {'time': '', 'opp': '', 'name': 'Jay Cutler', 'team': 'CHI'},
    {'time': '', 'opp': '', 'name': 'Andy Dalton', 'team': 'CIN'},
    {'time': '', 'opp': '', 'name': 'Nick Foles', 'team': 'STL'},
    {'time': '', 'opp': '', 'name': 'Sam Bradford', 'team': 'PHI'},
    {'time': '', 'opp': '', 'name': 'Teddy Bridgewater', 'team': 'MIN'},
    {'time': '', 'opp': '', 'name': 'Ryan Tannehill', 'team': 'MIA'},
    {'time': '', 'opp': '', 'name': 'Carson Palmer', 'team': 'ARI'},
    {'time': '', 'opp': '', 'name': 'E.J. Manuel', 'team': 'BUF'},
    {'time': '', 'opp': '', 'name': 'Jameis Winston', 'team': 'TB'}
]
qblist = [
    'Aaron Rodgers',
    'Andrew Luck',
    'Drew Brees',
    'Peyton Manning',
    'Russell Wilson',
    'Matthew Stafford',
    'Tom Brady',
    'Cam Newton',
    'Tony Romo',
    'Ben Roethlisberger',
    'Matt Ryan',
    'Derek Carr',
    'Phillip Rivers',
    'Johnny Manziel',
    'Jay Cutler',
    'Andy Dalton',
    'Nick Foles',
    'Sam Bradford',
    'Teddy Bridgewater',
    'Ryan Tannehill',
    'Carson Palmer',
    'E.J. Manuel',
    'Jameis Winston'
]

rbs = [
    {'time': '', 'opp': '', 'name': 'Adrian Peterson', 'team': 'MIN'},
    {'time': '', 'opp': '', 'name': 'LeSean McCoy', 'team': 'BUF'},
    {'time': '', 'opp': '', 'name': 'Eddie Lacy', 'team': 'GB'},
    {'time': '', 'opp': '', 'name': 'LeVeon Bell', 'team': 'PIT'},
    {'time': '', 'opp': '', 'name': 'DeMarco Murray', 'team': 'DAL'},
    {'time': '', 'opp': '', 'name': 'Matt Forte', 'team': 'CHI'},
    {'time': '', 'opp': '', 'name': 'Jamaal Charles', 'team': 'KC'},
    {'time': '', 'opp': '', 'name': 'Marshawn Lynch', 'team': 'SEA'},
    {'time': '', 'opp': '', 'name': 'Arian Foster', 'team': 'HOU'},
    {'time': '', 'opp': '', 'name': 'Tre Mason', 'team': 'STL'},
    {'time': '', 'opp': '', 'name': 'Mark Ingram', 'team': 'NO'},
    {'time': '', 'opp': '', 'name': 'Justin Forsett', 'team': 'BAL'},
    {'time': '', 'opp': '', 'name': 'C.J. Anderson', 'team': 'DEN'},
    {'time': '', 'opp': '', 'name': 'Joique Bell', 'team': 'DET'},
    {'time': '', 'opp': '', 'name': 'Carlos Hyde', 'team': 'SF'},
    {'time': '', 'opp': '', 'name': 'Lamar Miller', 'team': 'MIA'},
    {'time': '', 'opp': '', 'name': 'Andre Ellington', 'team': 'ARI'},
    {'time': '', 'opp': '', 'name': 'Jeremy Hill', 'team': 'CIN'},
    {'time': '', 'opp': '', 'name': 'Alfred Morris', 'team': 'WAS'},
    {'time': '', 'opp': '', 'name': 'Latavius Murray', 'team': 'OAK'},
    {'time': '', 'opp': '', 'name': 'Isaiah Crowell', 'team': 'CLE'},
    {'time': '', 'opp': '', 'name': 'Rashad Jennings', 'team': 'NYG'},
    {'time': '', 'opp': '', 'name': 'Branden Oliver', 'team': 'SD'},
    {'time': '', 'opp': '', 'name': 'Giovani Bernard', 'team': 'CIN'},
    {'time': '', 'opp': '', 'name': 'Fred Jackson', 'team': 'BUF'},
    {'time': '', 'opp': '', 'name': 'Bishop Sankey', 'team': 'TEN'}
]
rblist = [
    'Adrian Peterson',
    'LeSean McCoy',
    'Eddie Lacy',
    'LeVeon Bell',
    'DeMarco Murray',
    'Matt Forte',
    'Jamaal Charles',
    'Marshawn Lynch',
    'Arian Foster',
    'Tre Mason',
    'Mark Ingram',
    'Justin Forsett',
    'C.J. Anderson',
    'Joique Bell',
    'Carlos Hyde',
    'Lamar Miller',
    'Andre Ellington',
    'Jeremy Hill',
    'Alfred Morris',
    'Latavius Murray',
    'Isaiah Crowell',
    'Rashad Jennings',
    'Branden Oliver',
    'Giovani Bernard',
    'Fred Jackson',
    'Bishop Sankey'
]

wrs = [
    {'time': '', 'opp': '', 'name': 'Calvin Johnson', 'team': 'DET'},
    {'time': '', 'opp': '', 'name': 'Odell Beckham', 'team': 'NYG'},
    {'time': '', 'opp': '', 'name': 'Alshon Jeffery', 'team': 'CHI'},
    {'time': '', 'opp': '', 'name': 'Antonio Brown', 'team': 'PIT'},
    {'time': '', 'opp': '', 'name': 'Demaryius Thomas', 'team': 'DEN'},
    {'time': '', 'opp': '', 'name': 'Jordy Nelson', 'team': 'GB'},
    {'time': '', 'opp': '', 'name': 'Julio Jones', 'team': 'ATL'},
    {'time': '', 'opp': '', 'name': 'A.J. Green', 'team': 'CIN'},
    {'time': '', 'opp': '', 'name': 'T.Y. Hilton', 'team': 'IND'},
    {'time': '', 'opp': '', 'name': 'Jeremy Maclin', 'team': 'KC'},
    {'time': '', 'opp': '', 'name': 'Randall Cobb', 'team': 'GB'},
    {'time': '', 'opp': '', 'name': 'Emmanuel Sanders', 'team': 'DEN'},
    {'time': '', 'opp': '', 'name': 'Mike Evans', 'team': 'TB'},
    {'time': '', 'opp': '', 'name': 'Kelvin Benjamin', 'team': 'CAR'},
    {'time': '', 'opp': '', 'name': 'DeAndre Hopkins', 'team': 'HOU'},
    {'time': '', 'opp': '', 'name': 'Brandon Marshall', 'team': 'NYJ'},
    {'time': '', 'opp': '', 'name': 'Jordan Matthews', 'team': 'PHI'},
    {'time': '', 'opp': '', 'name': 'Sammy Watkins', 'team': 'BUF'},
    {'time': '', 'opp': '', 'name': 'Golden Tate', 'team': 'DET'},
    {'time': '', 'opp': '', 'name': 'Julian Edelman', 'team': 'NE'},
    {'time': '', 'opp': '', 'name': 'Keenan Allen', 'team': 'SD'},
    {'time': '', 'opp': '', 'name': 'Vincent Jackson', 'team': 'TB'},
    {'time': '', 'opp': '', 'name': 'Kenny Stills', 'team': 'MIA'},
    {'time': '', 'opp': '', 'name': 'Mike Wallace', 'team': 'MIN'},
    {'time': '', 'opp': '', 'name': 'Davante Adams', 'team': 'GB'},
    {'time': '', 'opp': '', 'name': 'Martavis Bryant', 'team': 'PIT'},
    {'time': '', 'opp': '', 'name': 'Brandin Cooks', 'team': 'NO'},
    {'time': '', 'opp': '', 'name': 'Jarvis Landry', 'team': 'MIA'}
]
wrlist = [
    'Calvin Johnson',
    'Odell Beckham',
    'Alshon Jeffery',
    'Antonio Brown',
    'Demaryius Thomas',
    'Jordy Nelson',
    'Julio Jones',
    'A.J. Green',
    'T.Y. Hilton',
    'Jeremy Maclin',
    'Randall Cobb',
    'Emmanuel Sanders',
    'Mike Evans',
    'Kelvin Benjamin',
    'DeAndre Hopkins',
    'Brandon Marshall',
    'Jordan Matthews',
    'Sammy Watkins',
    'Golden Tate',
    'Julian Edelman',
    'Keenan Allen',
    'Vincent Jackson',
    'Kenny Stills',
    'Mike Wallace',
    'Davante Adams',
    'Martavis Bryant',
    'Brandin Cooks',
    'Jarvis Landry'
]

tes = [
    {'time': '', 'opp': '', 'name': 'Rob Gronkowski', 'team': 'NE'},
    {'time': '', 'opp': '', 'name': 'Jimmy Graham', 'team': 'SEA'},
    {'time': '', 'opp': '', 'name': 'Julius Thomas', 'team': 'JAC'},
    {'time': '', 'opp': '', 'name': 'Mychal Rivera', 'team': 'OAK'},
    {'time': '', 'opp': '', 'name': 'Dwayne Allen', 'team': 'IND'},
    {'time': '', 'opp': '', 'name': 'Travis Kelce', 'team': 'KC'},
    {'time': '', 'opp': '', 'name': 'Greg Olsen', 'team': 'CAR'},
    {'time': '', 'opp': '', 'name': 'Vernon Davis', 'team': 'SF'},
    {'time': '', 'opp': '', 'name': 'Coby Fleener', 'team': 'IND'},
    {'time': '', 'opp': '', 'name': 'Martellus Bennett', 'team': 'CHI'},
    {'time': '', 'opp': '', 'name': 'Eric Ebron', 'team': 'DET'},
    {'time': '', 'opp': '', 'name': 'Dennis Pitta', 'team': 'BAL'},
    {'time': '', 'opp': '', 'name': 'Austin Seferian-Jenkins', 'team': 'TB'},
    {'time': '', 'opp': '', 'name': 'Kyle Rudolph', 'team': 'MIN'},
    {'time': '', 'opp': '', 'name': 'Maxx Williams', 'team': 'N/A'}
]
telist = [
    'Rob Gronkowski',
    'Jimmy Graham',
    'Julius Thomas',
    'Mychal Rivera',
    'Dwayne Allen',
    'Travis Kelce',
    'Greg Olsen',
    'Vernon Davis',
    'Coby Fleener',
    'Martellus Bennett',
    'Eric Ebron',
    'Dennis Pitta',
    'Austin Seferian-Jenkins',
    'Kyle Rudolph',
    'Maxx Williams'
]

defsts = [
    {'time': '', 'opp': '', 'name': 'SEA', 'team': 'SEA'},
    {'time': '', 'opp': '', 'name': 'STL', 'team': 'STL'},
    {'time': '', 'opp': '', 'name': 'HOU', 'team': 'HOU'},
    {'time': '', 'opp': '', 'name': 'PHI', 'team': 'PHI'},
    {'time': '', 'opp': '', 'name': 'MIN', 'team': 'MIN'},
    {'time': '', 'opp': '', 'name': 'GB', 'team': 'GB'},
    {'time': '', 'opp': '', 'name': 'NE', 'team': 'NE'},
    {'time': '', 'opp': '', 'name': 'NYJ', 'team': 'NYJ'},
    {'time': '', 'opp': '', 'name': 'BAL', 'team': 'BAL'},
    {'time': '', 'opp': '', 'name': 'ARI', 'team': 'ARI'},
    {'time': '', 'opp': '', 'name': 'BUF', 'team': 'BUF'}
]
defstlist = [
    'SEA',
    'STL',
    'HOU',
    'PHI',
    'MIN',
    'GB',
    'NE',
    'NYJ',
    'BAL',
    'ARI',
    'BUF'
]